Repository Kritika30032002/Top_Secrets, pull requests merged in 2023-12, with the labels that each got.

#71 Fix: Renaming "/submit" routes fixes:- #68
  app.js
  views/secret-form.ejs
  views/secrets.ejs
Labels: easy

#76 Corrected Button UI
  public/css/styles.css
  views/home.ejs
  views/login.ejs
  views/secrets.ejs
Labels: Codepeak23, medium

#81 Fixed the login page layout and button ui
  views/login.ejs
Labels: Codepeak23, medium

#79 Fixed icons and visibility on dark backgrounds
  views/partials/footer.ejs
Labels: Codepeak23, easy

#94 added contribution and code of conduct file
  code_of_conduct.md
  contributing.md
Labels: kwoc

#93 removed scroll-to-top button from unnecessary files Fixes #84
  views/about.ejs
  views/home.ejs
  views/login.ejs
  views/register.ejs
  views/secrets.ejs
Labels: Codepeak23, medium

#105 Login alerts#90
  app.js
  views/login.ejs
  views/register.ejs
Labels: kwoc

#103 Redesigned and Formatted Complete Website.
  public/css/dark-styles.css
  public/css/styles.css
  views/about.ejs
  views/home.ejs
  views/login.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
  views/register.ejs
  views/secret-form.ejs
  views/secrets.ejs
Labels: Codepeak23, BONUS

#120 Enhance README.md for new contributors
  .env.example
  README.md
  app.js
Labels: Codepeak23, medium

#127 Update .env.example #126
  .env.example
Labels: Codepeak23, 1 point

#141 regulated a the color theme of register and login button on toggling the dark mode button.
  app.js
  public/css/dark-styles.css
  public/css/styles.css
Labels: Codepeak23, 1 point
